name: Compilation
on:
  pull_request:
    types: [opened, reopened, synchronized, edited]
  push:
    branches:
      - 'dev'
      - 'main'
jobs:
  compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Compile
        run: make
