name: tests
on:
  push:
    branches:
      - '*'
      - '!*WIP'
jobs:
  linux-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
        with:
          submodules: recursive
      - name: Run Tests
        working-directory: ./test
        run: |
          make
          ./test.out
