name: Tests
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - 'dev'
      - 'main'
  push:
    branches:
      - 'dev'
      - 'main'
jobs:
  make-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run Tests
        working-directory: ./test
        run: |
          make
          ./test.out
